# Generated by Django 4.1 on 2023-06-03 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 6, 3, 18, 27, 11, 710080))),
                ('text', models.TextField(max_length=150)),
            ],
        ),
    ]
