# Generated by Django 4.1 on 2023-06-04 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 6, 23, 37, 821002, tzinfo=datetime.timezone.utc)),
        ),
    ]
